### ISSUE TITLE
Wrong link to .jar file

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#100]
**Describe the bug**
the link provided in User Guide should link to the team repo. But was linked to AB4 instead

**To Reproduce**
1. Go to 'User Guide'
2. Click on '"here" in Quick Start point 2'

**Expected behavior**
The link should be to the team repo or .jar file instead

**Screenshots**
![image](https://user-images.githubusercontent.com/35739423/47905160-5e7b6680-dec1-11e8-831d-3e9981f77a39.png)
![image](https://user-images.githubusercontent.com/35739423/47905185-6f2bdc80-dec1-11e8-85ea-d51c18e6f85c.png)

**Additional context**

<hr>

**Reported by:** @chuazhenwei
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#21]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding **an incorrect link in our User Guide**.

I have looked into the bug as mentioned, and **fixed the incorrect link**:
![image](https://user-images.githubusercontent.com/35021368/47947894-adc4a400-df60-11e8-9848-3c126ba06f1c.png)

Thank you for your time in reporting this bug!

Geng Yu
