### ISSUE TITLE
wrong command in UG.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#101]
Describe the bug
As described in topic. The example provided in UG doesnt work at all. i assume UG is not updated.

To Reproduce
help
quick start, pointer 6.
enter command.
Expected behavior
Expected to delete INDEX 3

Screenshots
![image](https://user-images.githubusercontent.com/26619858/47905244-9387b900-dec1-11e8-867a-075abfaeec81.png)
![image](https://user-images.githubusercontent.com/26619858/47905262-a0a4a800-dec1-11e8-9231-776bb40219e7.png)

Additional context
nope.

<hr>

**Reported by:** @cjunxiang
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#31]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding an **incorrect example command under the Quick Start section in our User Guide**.

I have looked into the bug as mentioned, and **fixed the incorrect example command**:
![image](https://user-images.githubusercontent.com/35021368/47947886-7fdf5f80-df60-11e8-9f18-892426918e98.png)

Thank you for your time in reporting this bug!

Geng Yu
