### ISSUE TITLE
Show a welcome screen to tell me what is going on lol 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#102]
**Please describe the problem**
It is very confusing to have a lot of calenders. It would be nice to have a welcome message to tell me what state i am in.

**Describe the improvement you'd like to suggest**
Simply a one-liner to tell me that the files have loaded.

**Additional context**

<hr>

**Reported by:** @cjunxiang
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#43]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your suggestion regarding a **clearer layout representation for users**.

We acknowledge that our current application has a lack of placeholders for the different items listed, and we plan to **add the following placeholders** in our next release:

![image](https://user-images.githubusercontent.com/35021368/47947926-5bd04e00-df61-11e8-830a-e39d9c189507.png)

Thank you for your time in to bring us this suggestion!

Geng Yu
