### ISSUE TITLE
Merge Command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#103]
**Please describe the problem**
I was able to merge the same index number twice i.e merge n/1 n/1 n/test

**Describe the improvement you'd like to suggest**
Prevent users from merging the same index twice.

**Additional context**
There's no point in merging 1 person twice, the user might have accidentally keyed in a wrong number.

<hr>

**Reported by:** @kohjunkiat
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#68]</sub>

**Comment by leegengyu** [comment]
Hello @kohjunkiat!

Thank you for your bug report regarding the **ability to merge the same person's time-table twice**.

We acknowledge that this was something which we missed out, and we will ensure that **users are not able to merge the same person's time-table twice** in the next release. In the event that the user attempts to do so, **an error message would be conveyed to the user**.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by tonykoh** [comment]
Hi Gengyu, thanks for your response!

Actually after some pondering it might still be **good to have** to allow someone's timetable to be merged twice. For ie, if someone is deemed more important in the meeting, users might want to merge his timetable twice to account for the priority. 

Anyway, these are just my 3cents point of view! Allow me to apologise beforehand if some of the reports are overly nit-picking.

Jun Kiat

**Comment by leegengyu** [comment]
Hi @kohjunkiat!

That is a valid use case to be considered as well, albeit merging one person's timetable twice might be a crude way to do so. My team and I will look into this nonetheless!

Thank you once again!

Geng Yu

**Comment by E0201942** [comment]
Decided to leave in for this release as a way to increase someone's importance inelegantly. Plan to create an importance Class for next release that will automatically account for how important someone is.
