### ISSUE TITLE
Include side scrolling for users info

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#105]
**Please describe the problem**
unable to see full information

**Describe the improvement you'd like to suggest**
provide side scrolling or hover to show the full details that are too long

**Additional context**
![image](https://user-images.githubusercontent.com/35739423/47905642-8c14df80-dec2-11e8-89e8-602eb6916f5f.png)

<hr>

**Reported by:** @chuazhenwei
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#87]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding **information that is cut-off from the display**.

We acknowledge that this was a design implementation issue that was missed out, and we will put **a restriction on the length of the respective user fields before our next release**.

Thank you for your time in reporting this bug!

Geng Yu
