### ISSUE TITLE
findmain and findmerge function returns UNKNOWN COMMAND

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#106]
**Describe the bug**
findmain and findmerge function returns UNKNOWN COMMAND.

**To Reproduce**
1. input `find`
2. the program shows guide.

Parameters: LIST(main, merged) KEYWORD [MORE_KEYWORDS]...
Example: findmain alice bob charlie

3. input `findmain alice`, `findmerged alice`, `listmain alice`, `listmain alice.` 
4. all doesnt work

**Expected behavior**
I should be able to have filtered the list for my keywords.

**Screenshots**
![image](https://user-images.githubusercontent.com/26619858/47905541-5839ba00-dec2-11e8-8b2a-a685d87563f5.png)
![image](https://user-images.githubusercontent.com/26619858/47905652-8e773980-dec2-11e8-93fc-73b9b2fc87b9.png)
![image](https://user-images.githubusercontent.com/26619858/47905668-9800a180-dec2-11e8-8ba2-7ca43d7e3624.png)
![image](https://user-images.githubusercontent.com/26619858/47905673-9fc04600-dec2-11e8-8200-f55f2790387e.png)

**Additional context**
I assume is a parser error.

<hr>

**Reported by:** @cjunxiang
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#97]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding the **functionality of our find and list command**.

A similar issue has been raised in #104, and we will fix the **mix-ups with the find and list commands** before the next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Duplicate issue.
