### ISSUE TITLE
Delete command not working according to User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#107]
**Describe the bug**
Delete command is not working according to your User Guide

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your main application
2. Type in `delete 1`
3. See the error message in the command box
4. Go to section `3.2.6. Deleting a person: delete` in your User Guide, according to the description, the delete command is not working

**Expected behavior**
Delete command should work with `delete INDEX`

**Screenshots**
Check the following screenshot:
<img width="1280" alt="delete not working" src="https://user-images.githubusercontent.com/32096360/47905780-e0b85a80-dec2-11e8-931b-e5ee9517e05a.png">

<hr>

**Reported by:** @aaryamnus
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#120]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your bug report regarding a **misrepresentation in our application versus our User Guide**.

I have looked into the bug as mentioned, and **corrected the delete command portion of our User Guide**:
![image](https://user-images.githubusercontent.com/35021368/47948101-08f89580-df65-11e8-990d-1cc9be8ab2ba.png)

Thank you for your time in reporting this bug!

Geng Yu
