### ISSUE TITLE
`Select 1` selects users' calender as well

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#108]
**Describe the bug**
Select 1 should select calendar INDEX 1, however it selects the user's calendar too. 
Select 2 successfully selects only INDEX 2

**To Reproduce**
1. type `select 1`
2. viola

**Expected behavior**
to select only INDEX 1

**Screenshots**
![image](https://user-images.githubusercontent.com/26619858/47905824-fc236580-dec2-11e8-83ea-c702baaa144f.png)

**Additional context**
depending on your backend logic, this might snowball into alot of issues. 

<hr>

**Reported by:** @cjunxiang
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#128]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding our **faulty select command**.

I have looked into the bug as mentioned, and the **merged contact of index 1 is selected as well, in addition to the self entry and the main contact list index 1**:
![image](https://user-images.githubusercontent.com/35021368/47948112-39d8ca80-df65-11e8-9bd2-e5b81be9a1e4.png)

We will fix it before our next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Select command fixed
