### ISSUE TITLE
Change Command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#109]
**Describe the bug**
When I try to change a negative index for i.e **change -1 mon 9am hello** they app does not do anything when I press enter

**To Reproduce**
Enter **change -1 mon 9am hello**

**Expected behavior**
An error message to indicate invalid index number

**Screenshots**
nil

**Additional context**
nil

<hr>

**Reported by:** @kohjunkiat
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#141]</sub>

**Comment by leegengyu** [comment]
Hello @kohjunkiat!

Thank you for your bug report regarding our **change command that did not handle negative integers**.

I have looked into the bug as mentioned, and indeed there is **no change in display (ie no message) if such an input is given by the user.**

We will ensure that **an error message is displayed to the user if a negative input is received for the change command** before our next release.

Screenshot of the bug:
![image](https://user-images.githubusercontent.com/35021368/47948241-f6cc2680-df67-11e8-80b7-fbf26ba44cf5.png)

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Exception added to handle this bug. Correct error message will not display
