### ISSUE TITLE
Wrong error message.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#110]
**Describe the bug**
Wrong error messages for invalid command.

**To Reproduce**
1. Go to 'Command text box'
2. Type in the command 'edit 1 n/tom p/123456 ta/s'
3. Scroll down to 'Message box showing "Phone numbers should only contain numbers, and it should be at least 3 digits long"'

**Expected behavior**
When wrong command is given, the invalid command message should be shown instead of the constraint message for a command.

**Screenshots**
![image](https://user-images.githubusercontent.com/35739423/47906084-75bb5380-dec3-11e8-953f-a5d351233fe7.png)

**Additional context**

<hr>

**Reported by:** @chuazhenwei
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#158]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding our **incorrect error message for a wrong input for the edit command**.

I have looked into the bug as mentioned, and we will ensure that the correct error message is displayed to the user in such a scenario before the next release, ie the **error message should display the incorrect parameter accurately**.

Thank you for your time in reporting this bug!

Geng Yu
