### ISSUE TITLE
Delete guide is WRONG

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#111]
**Describe the bug**
took me awhile to figure out how to delete ;_;

**To Reproduce**
1. type `delete` and enter
2. follow guide.
3. give up.
4. type `help`
5. navigate to delete. guide says `delete INDEX`
6. guide in app says Example: `deletemerged  1`
7. figure out it's `delete [SPACE] merged [INDEX]`

**Expected behavior**
delete something 

**Screenshots**

![image](https://user-images.githubusercontent.com/26619858/47906101-7f44bb80-dec3-11e8-93e1-e5ef3aa3d6fc.png)

successful delete:
![image](https://user-images.githubusercontent.com/26619858/47906136-8d92d780-dec3-11e8-8409-a185f9ffcda4.png)

**Additional context**
pls update UG.

<hr>

**Reported by:** @cjunxiang
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#168]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding an **incorrect example for the delete command in our User Guide**.

I have looked into the bug as mentioned, and **have fixed it accordingly in #101** (as raised earlier on by you).

Thank you for your time in reporting this bug!

Geng Yu
