### ISSUE TITLE
unable to add or edit tags that contain spaces

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#112]
Does not allow for spaces to be included in tags

1. assume there are already names inside
2. edit on the 2nd person by entering edit 2 t/Best Friend
3. command box returns invalid command

**Expected behavior**
should be expected to add/edit tags not properly stated in user guide

<img width="1396" alt="screenshot 2018-11-02 at 17 14 13" src="https://user-images.githubusercontent.com/35647345/47906127-88ce2380-dec3-11e8-90ff-e7b4bab8140e.png">

<hr>

**Reported by:** @kianmengtan
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#169]</sub>

**Comment by leegengyu** [comment]
Hello @kianmengtan!

Thank you for your bug report regarding a **wrong error message displayed to user when editing a tag**.

I have looked into the bug as mentioned, and we acknowledge that we did not **take into account of white-spaces for tags for a user**. We are currently phasing out the use of tags for a user and we will fix it by the next release.

Thank you for your time in reporting this bug!

Geng Yu
