### ISSUE TITLE
Incorrect error message when INDEX is not an integer

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#113]
**Describe the bug**
The error message for the `select` command is incorrect when the `INDEX` is out of range of integer values.

**To Reproduce**
1. Go to your main book
2. Type in a command such as `select 18309182301298310238109381038103812080938103281209381029381`
3. See the error, it is provided in the screenshot in this Issue

**Expected behavior**
The error message should instead be `The person index provided is invalid`

**Screenshots**
<img width="730" alt="select index out of range" src="https://user-images.githubusercontent.com/32096360/47906046-61775680-dec3-11e8-9f6c-6734a7a88836.png">

**Additional context**

<hr>

**Reported by:** @aaryamnus
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#183]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your bug report regarding our **incorrect error message for a large integer for the select command**.

I have looked into the bug as mentioned, and we will ensure that a **more detailed and accurate error message is raised, if the user enters an invalid positive integer for the select command**.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Duplicate issue.
