### ISSUE TITLE
Find command does not work as per mentioned in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#114]
**Describe the bug**
Based on the example given in user guide, the command "find John" will return anyone with the name "John" in them (case-insensitive). However invalid command are shown instead

**To Reproduce**
1. Go to 'Command text box'
2. Type 'find John'
3. See error

**Expected behavior**
Shown anyone with the name john.

**Screenshots**
![image](https://user-images.githubusercontent.com/35739423/47906478-48bb7080-dec4-11e8-8327-f70fc3dd9ced.png)

**Additional context**

<hr>

**Reported by:** @chuazhenwei
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#231]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding the **misrepresentation of our find command in the User Guide versus the application**.

A similar issue has been raised in #104, and we have fixed the inaccuracies in the User Guide to match how it should work.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Duplicate Issue.
