### ISSUE TITLE
find command not working 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#115]
**Describe the bug**
Find command not working

**To Reproduce**
1. Alice was added already in the list
2. user enters command 'findmain alice'
3. command box returns invalid command
4. error

**Expected behavior**
expected to see only Alice's name on a list?

**Screenshots**
<img width="1431" alt="screenshot 2018-11-02 at 17 22 56" src="https://user-images.githubusercontent.com/35647345/47906611-9932ce00-dec4-11e8-9d11-74ace4cb6bd8.png">
<img width="1431" alt="screenshot 2018-11-02 at 17 23 21" src="https://user-images.githubusercontent.com/35647345/47906637-a3ed6300-dec4-11e8-9491-1562faffdc84.png">

**Additional context**

<hr>

**Reported by:** @kianmengtan
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#283]</sub>

**Comment by leegengyu** [comment]
Hello @kianmengtan!

Thank you for your bug report regarding our **faulty find command**.

I have looked into the bug as mentioned, and there should be a **white-space between "find" and "main/merge" for the example shown in the application**. A similar issue has been raised in #106 and we will fix the bug before our next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Duplicate issue.
