### ISSUE TITLE
Invalid phone number

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#116]
The add command allows phone number of any length to be enter, hence even if i enter a phone number that is 1000 digits long it will accept. However the phone number in the GUI will be cut off as it is too long

To improvement you can limit the length of phone number

<hr>

**Reported by:** @kohjunkiat
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#286]</sub>

**Comment by leegengyu** [comment]
Hello @kohjunkiat!

Thank you for your bug report regarding **information that is cut-off from the display**.

We acknowledge that this was a design implementation issue that was missed out, and we will **put a restriction on the length of the respective user fields before our next release**.

A similar issue was raised in #105.

Thank you for your time in reporting this bug!

Geng Yu
