### ISSUE TITLE
Share function (both private and public) and guide mismatch 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#117]
**Describe the bug**
mismatch of commmands.
guide says 
![image](https://user-images.githubusercontent.com/26619858/47906457-3fca9f00-dec4-11e8-9639-e5d095b89bdb.png)

help says
![image](https://user-images.githubusercontent.com/26619858/47906475-478a4380-dec4-11e8-9342-cdd94e8e7369.png)

example given 
![image](https://user-images.githubusercontent.com/26619858/47906483-4ce78e00-dec4-11e8-8aff-fd6e4882dd2f.png)

**To Reproduce**
1. just try all the above screen shots LOL.
2. only one works. 

**Expected behavior**
copy to my clip board.

**Screenshots**
refer to abv

**Additional context**
successful backend tho, but all commands are conflicting.

successfull: 
mon 8am GER1000 mon 9am GER1000 mon 10am free mon 11am free mon 12pm free mon 1pm free mon 2pm nothing mon 3pm free mon 4pm free mon 5pm free mon 6pm free mon 7pm nothing tue 8am CS2040c tue 9am CS2040c tue 10am ST2332 tue 11am ST2332 tue 12pm free tue 1pm free tue 2pm CS2107 tue 3pm CS2107 tue 4pm free tue 5pm free tue 6pm free tue 7pm free wed 8am CS2101 wed 9am CS2101 wed 10am free wed 11am free wed 12pm GES1041 wed 1pm GES1041 wed 2pm free wed 3pm free wed 4pm CS2113 wed 5pm CS2113 wed 6pm free wed 7pm free thu 8am free thu 9am free thu 10am MA1521 thu 11am MA1521 thu 12pm free thu 1pm free thu 2pm CS2040c thu 3pm CS2040c thu 4pm free thu 5pm free thu 6pm free thu 7pm free fri 8am free fri 9am free fri 10am CS2107 fri 11am free fri 12pm free fri 1pm free fri 2pm CS2101 fri 3pm free fri 4pm free fri 5pm free fri 6pm free fri 7pm free 

<hr>

**Reported by:** @cjunxiang
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#287]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding our **share command**.

We acknowledge that there was a **mismatch of commands as mentioned**. The **share command will be phased out in the next release** as we have got our import and export commands ready, and the share command will be replaced.

We apologise for the inconvenienced caused!

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Share function removed.
