### ISSUE TITLE
delete command not working

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#118]
**Describe the bug**
unable to delete person 

**To Reproduce**
1. enter 'list'
2. wants to delete 2nd person by entering delete 2
3. command box shows error

**Expected behavior**
expected to see the 2nd person removed from list

**Screenshots**
<img width="1413" alt="screenshot 2018-11-02 at 17 30 20" src="https://user-images.githubusercontent.com/35647345/47906832-06defa00-dec5-11e8-945f-725f31bdcb96.png">

**Additional context**
user guide suggested:
list 
delete 2

but in app the example gives deletemerged 1, not sure which to follow

<hr>

**Reported by:** @kianmengtan
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#334]</sub>

**Comment by leegengyu** [comment]
Hello @kianmengtan!

Thank you for your bug report regarding an **incorrect example for the delete command in our User Guide and the application**.

A similar issue has been raised in #101, and we have corrected the bug accordingly.

Thank you for your time in reporting this bug!

Geng Yu
