### ISSUE TITLE
find command error message invalid examples of command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#119]
**Describe the bug**
Invalid command format error message for find command show a example format for using the find command. However the example itself gets a return of unknown command message.

**To Reproduce**
1. Go to 'command text box'
2. Type in 'find' to see the invalid command format message
3. Scroll down to view the example that say "Example: findmain alice bob charlie"
4. Type the example in command box.

**Expected behavior**
supposed to show 0 person since there are no one with the name of alice in the default database.

**Screenshots**
![image](https://user-images.githubusercontent.com/35739423/47906958-40b00080-dec5-11e8-881b-5f1ae209599a.png)
![image](https://user-images.githubusercontent.com/35739423/47906971-4b6a9580-dec5-11e8-81f0-4b8df537fd8e.png)

**Additional context**

<hr>

**Reported by:** @chuazhenwei
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#342]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding the **functionality of our find command**.

A similar issue has been raised in #106, and we will **fix the mix-ups with the find command** before the next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
The error messages have been fixed.
