### ISSUE TITLE
Invalid input does not return exception

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#120]
**Describe the bug**
Using filter function, UG and guide says that inputs MUST be a day and a time.
when input invalid strings, they still accept it and return "0 persons listed"

**To Reproduce**
1. `filter [ANY STRING] 6pm`
2. no exceptions.

**Expected behavior**
An exception should have been show to tell users of a illegal input

**Screenshots**
![image](https://user-images.githubusercontent.com/26619858/47906929-32fa7b00-dec5-11e8-9bef-f22df9c07605.png)
![image](https://user-images.githubusercontent.com/26619858/47907017-65a47380-dec5-11e8-918f-1dec40ce85e8.png)

**Additional context**

<hr>

**Reported by:** @cjunxiang
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#351]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding **inaccurate messages being displayed for an incorrect input for the filter command**.

We acknowledge that we had **not taken the incorrect input cases into account yet**, and we will fix the bug by the next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
The command will only check for a time if a valid day ie.  (mon, tue, wed, thu, fri) is inputted before it. If not, it gets treated as an activity and will be filtered as such. User guide has been updated to reflect this.
