### ISSUE TITLE
Find command not working

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#121]
**Describe the bug**
Unable to use find command

**To Reproduce**
find alex

**Expected behavior**
All person with alex listed

**Screenshots**
![image](https://user-images.githubusercontent.com/35600447/47907052-7654e980-dec5-11e8-829b-c15ed1632112.png)

<hr>

**Reported by:** @kohjunkiat
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#366]</sub>

**Comment by leegengyu** [comment]
Hello @kohjunkiat!

Thank you for your bug report regarding the **functionality of our find command**.

A similar issue has been raised in #106, and we will **fix the mix-ups with the find command** before the next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
User guide has been updated
