### ISSUE TITLE
As a user i want to be able to see when i am free when SOMEONE else is free

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-W12-2/main#122]
**Please describe the problem**
using the free function, i am only able to see the common free time between different people. but when i f/self, it doesnt work. It would be nice because ultimately users want to check if they themselves have common timeslots.

**Describe the improvement you'd like to suggest**
As per above.

**Additional context**
![image](https://user-images.githubusercontent.com/26619858/47907289-e4011580-dec5-11e8-87dd-aa88631051bc.png)

<hr>

**Reported by:** @cjunxiang
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#408]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your suggestion regarding the **functionality of our free command**.

We acknowledge that it would definitely **be great if the free command can be used to accommodate the self time-table**, in addition to the current ability to find a free slot across listed contacts. We will implement it before the next release.

Thank you for your time in giving this suggestion!

Geng Yu
