### ISSUE TITLE
Invalid delete function

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-W12-2/main#123]
**Describe the bug**
The user guide mention the delete function will delete the person at specified index. However, invalid command format are detected instead

**To Reproduce**
1. Go to 'Command Text Box'
2. Type in "list"
3. Type in "delete 8"

**Expected behavior**
the person at INDEX 8 gets deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/35739423/47907280-e06d8e80-dec5-11e8-9384-c464c5c82fc3.png)
![image](https://user-images.githubusercontent.com/35739423/47907313-f5e2b880-dec5-11e8-8f88-ccaa671cedf3.png)

**Additional context**

<hr>

**Reported by:** @chuazhenwei
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#418]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding a **misrepresentation in our application versus our User Guide**.

I have looked into the bug as mentioned, and the bug has been fixed earlier in #107.

Thank you for your time in reporting this bug!

Geng Yu
