### ISSUE TITLE
Incorrect error message when `free` command INDEX is out of bounds

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#124]
**Describe the bug**
The error message for the `free` command is incorrect when INDEX is out of bounds

**To Reproduce**
1. Go to your application
2. Type in `filter f/-1`
3. See error

**Expected behavior**
Instead, it should be that the INDEX provided is incorrect

**Screenshots**
<img width="1280" alt="incorrect free error message" src="https://user-images.githubusercontent.com/32096360/47907211-bb791b80-dec5-11e8-81eb-a0e47cbb020a.png">

<hr>

**Reported by:** @aaryamnus
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#423]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your bug report regarding **inaccurate messages being displayed for an incorrect input for the filter command**.

We acknowledge that we had **not taken the incorrect input cases into account yet**, and we will fix the bug by the next release. A similar issue has been raised in #120.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Free command was referenced when filter command was being use. Filter and free command have different functionalities
