### ISSUE TITLE
Select Command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#125]
**Please describe the problem**
Current when i select anyone it just loads the google home page

**Describe the improvement you'd like to suggest**
Maybe consider having linken or ig profile link and load them instead, or simply change to a search on the person name.

<hr>

**Reported by:** @kohjunkiat
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#436]</sub>

**Comment by leegengyu** [comment]
Hello @kohjunkiat!

Thank you for your suggestion regarding our **Google placeholder upon executing the select command**.

We acknowledge that we are still **working on a feature in place of the Google placeholder**, ie the notes downloader, and it would definitely be better to have something in-place of the search engine (which would be out-of-place).

Thank you for your time in giving this suggestion!

Geng Yu

**Comment by E0201942** [comment]
Select command fixed, UI changed
