### ISSUE TITLE
No description of how to format string in command Import

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#127]
**Describe the bug**
There is no mention of how the string format should be for `import` commands, so if a user only wants to import a string, they will not know how to format it. 

**To Reproduce**
1. Go to your application
2. Try your `import` function, *without* doing your `export` function
3. See the error message
4. How must one format the string for the `import` function to work? The user is not able to use the `import` function without depending on the `export` function.

**Expected behavior**
Some description in the User Guide should be given on how to format the string message, or it should be stated that the `import` function cannot be used on its own

**Screenshots**
<img width="1280" alt="import string" src="https://user-images.githubusercontent.com/32096360/47907491-57a32280-dec6-11e8-8559-611f35ad73ea.png">

<hr>

**Reported by:** @aaryamnus
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#491]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your suggestion regarding the **use of our import function, and its description as stated on the User Guide**.

We acknowledge that there is currently **insufficient information on the import function on the User Guide**, as well as a **lack of detail in the error message displayed to the user on the application**.

We will work on these 2 ideas before the next release.

Thank you for your time in giving this suggestion!

Geng Yu
