### ISSUE TITLE
Case insensitive command accpetance

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#129]
**Please describe the problem**
`clearnotes` returns unknown command, while expected was `clearNotes`. would be nice as a improvement

**Describe the improvement you'd like to suggest**
just case insentitive

**Additional context**
![image](https://user-images.githubusercontent.com/26619858/47907954-3a228880-dec7-11e8-8ad1-50eec60589a2.png)

<hr>

**Reported by:** @cjunxiang
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#568]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding the **case-insensitivity of the clearNotes command**.

We acknowledge that it would definitely be better to **make it case-insensitive** for the convenience of the user, as well as remove the effort to explicitly key in an upper-case character in a command that is made up all (but one) lower-case characters.

We will make it case-insensitive before the next release.

Thank you for your time in giving this bug report!

Geng Yu

**Comment by ABearPerson** [comment]
Not a bug, QOL improvement request
