### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#130]
**Describe the bug**
When I manually duplicate a person in your storage file addressbook.xml. When I reload the app, all data will be lost.

**To Reproduce**
1. Open addressbook.xml
2. Duplicate any person
3. Reboot app.

**Expected behavior**
The app to handle the duplicate entry instead of deleting the entire data.

<hr>

**Reported by:** @kohjunkiat
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#588]</sub>

**Comment by leegengyu** [comment]
Hello @kohjunkiat!

Thank you for your bug report regarding the **non-handling of duplication of entries in our storage file, addressbook.xml**.

We acknowledge that we had not taken this scenario into consideration, and we will **work out an error-handling** for this before our next release.

Thank you for your time in giving this bug report!

Geng Yu
