### ISSUE TITLE
Criteria of duplicated persons should be written in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#131]
**Describe the bug**
If I were to add a person with the same name but different `address` or `tags` or `phone number`, the system does not accept this new person and claims it is a duplicate. 

**To Reproduce**
1. Go to your application
2. Clear your addressbook, and add a person using the command `add n/John Dof p/98765431 e/johne@example.com a/John street, block 123, #01-06`
3. Next, add another person using the following commands : `add n/John Dof p/98765331 e/johne@example.com a/John street, block 123, #01-06`, or `add n/John Dof p/98765431 e/johne@example.com a/Jobn street, block 123, #01-06`, or `add n/John Dof p/98765431 e/johae@example.com a/John street, block 123, #01-06`

**Expected behavior**
A clear criteria should be written as to when the application will not accept duplicate persons (by name, by address?). Currently two people with the same name cannot be added to your application. 

**Screenshots**
<img width="1279" alt="add command criteria" src="https://user-images.githubusercontent.com/32096360/47908225-bfa63880-dec7-11e8-8871-cef8ca16a721.png">

<hr>

**Reported by:** @aaryamnus
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#652]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your bug report to **make our User Guide clearer when it comes to adding a new user (with different user fields) of the same name as an existing user**.

We acknowledge that we had not made this clear on our User Guide previously, and we have made it explicit to the user on the User Guide now:
![image](https://user-images.githubusercontent.com/35021368/47948690-94c3ef00-df70-11e8-94ea-f1b773cd4594.png)

We may consider **allowing users with the same name but different user fields to be entered into the database** in future releases.

Thank you for your time in giving this bug report!

Geng Yu
