### ISSUE TITLE
find function shows irrelevant data (inaccurate search)

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#132]
**Describe the bug**
No persons are displayed when list.

**To Reproduce**
1. `list alice`
2. returned "1 persons/groups listed."
3. no groups or persons though..... the groups don't include any alice.

**Expected behavior**
someone to appear?

**Screenshots**
notice how there's no "alice" in the group.
![image](https://user-images.githubusercontent.com/26619858/47908286-dea4ca80-dec7-11e8-9d30-f3567d414de0.png)

**Additional context**

<hr>

**Reported by:** @cjunxiang
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#666]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding the **functionality of our list command**.

I have looked into the bug you mentioned, but we **do not support additional parameters for the list command** as shown in our User Guide:
![image](https://user-images.githubusercontent.com/35021368/47948696-c50b8d80-df70-11e8-89a7-8a3a586c5ec4.png)

Nonetheless, we will **implement an error message that will be shown to the user if additional parameters are entered for the list command**.

Thank you for your time in giving this bug report!

Geng Yu
