### ISSUE TITLE
Right part of the UI is redundant

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#133]
**Please describe the problem**
The right part of the UI with the Google Login screen is redundant.

**Describe the improvement you'd like to suggest**
You could remove this UI part and make better use of the calendar format to ensure that it's easy to read for the user. Currently, the distinction between the `self` and the `main` can become unclear. 

<hr>

**Reported by:** @aaryamnus
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#683]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your suggestion regarding our **Google placeholder on the right part of the UI**.

We acknowledge that we are still working on a feature in place of the Google placeholder, ie the notes downloader, and it would definitely be better to have something in-place of the search engine (which would be out-of-place). A similar suggestion has been given in #125.

Thank you for your time in giving this suggestion!

Geng Yu

**Comment by E0201942** [comment]
Main contact list has been shifted to occupy the entire right side and group contact list is now on the left under self.
