### ISSUE TITLE
Phone number input not filtered. (may be a improvement instead of bug)

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#134]
**Describe the bug**
a 6 digit phone number passes

**To Reproduce**
1. `add n/alice p/965432 e/johnd@example.com a/000, Clementi Ave 2, #02-25 t/friends t/owesMoney em/CS2101 em/CS2113T` 

**Expected behavior**
should have returned an exception or something

**Screenshots**
![image](https://user-images.githubusercontent.com/26619858/47908463-380cf980-dec8-11e8-9bfd-bdac6f6a8bc0.png)

**Additional context**

<hr>

**Reported by:** @cjunxiang
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#722]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your suggestion regarding our **restrictions on the number of digits for a phone number**.

While we have **not stated any limitations or criteria on the number of digits that a user can enter for their phone number**, we will bear in mind to **do so** before the next release. Our intention is not to limit the phone number to being strictly 8-digits, as this would mean that we are restricting the use of this application to only the Singapore audience.

Users might want to use the phone number field to store a number of their choice as well (albeit the fact that this deviates from the original intent of the field).

Thank you for your time in giving this suggestion!

Geng Yu
