### ISSUE TITLE
Inaccurate filter function

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#135]
**Describe the bug**
When filtering students with modules "CS2040c", 5 students with CS2040c as modules are shown. But when filtering students with modules "CS2040c" on "tue 9am", 7 students are shown instead. including 2 student with empty schedule

**To Reproduce**
1. Go to 'Command text box'
2. Type "filter CS2040c"
3. Scroll down to see 5 students listed with all having CS2040c in calendar
4. Go to 'Command text box'
5. Type "filter CS2040c tue 9am"
6. Scroll down to see 7 students listed with 2 of them having empty calendar

**Expected behavior**
Still show only 5 students with cs2040c modules in calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/35739423/47908531-5672f500-dec8-11e8-80c5-987ae62db270.png)
![image](https://user-images.githubusercontent.com/35739423/47908550-668ad480-dec8-11e8-92a9-84f51b847089.png)

**Additional context**

<hr>

**Reported by:** @chuazhenwei
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#740]</sub>

**Comment by leegengyu** [comment]
Hello @ChuaZhenWei!

Thank you for your bug report regarding the **functionality of our filter command**.

I have looked into the bug as mentioned, and we acknowledge that the **filter command has yet to be fully functional at this point in time**. We will work towards having it ready before the next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Issue has been fixed.
