### ISSUE TITLE
Misrepresentation of examples: conflicts what is shown in the app

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#99]
**Describe the bug**
As described in topic. The example provided in UG doesnt work at all. i assume UG is not updated. 

**To Reproduce**
1. `help`
2. quick start, pointer 6.
3. enter command.

**Expected behavior**
Expected to add new person

**Screenshots**
![image](https://user-images.githubusercontent.com/26619858/47905091-33911280-dec1-11e8-9203-dc1514682dc6.png)
![image](https://user-images.githubusercontent.com/26619858/47905111-40ae0180-dec1-11e8-8cbe-744385fcf624.png)

**Additional context**
nope.

<hr>

**Reported by:** @cjunxiang
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#16]</sub>

**Comment by leegengyu** [comment]
Hello @cjunxiang!

Thank you for your bug report regarding a **misrepresentation in our application versus our User Guide**.

I have looked into the bug as mentioned, and found out that it is a **missing white-space** in the command that you have typed, that is causing the "Unknown command" message.

In the first part of the command, you have typed "addn/John ..."
It is stated on our User Guide that it should be "add n/John ..." instead.

Attached is a screenshot of what I have just tested in accordance with our User Guide:
![image](https://user-images.githubusercontent.com/35021368/47947440-8e754900-df57-11e8-8541-a24aa08bf677.png)

Thank you for your time in reporting this bug!

Geng Yu
